### ISSUE TITLE
Add trailing slash to plugin_path config

### ISSUE THREAD

**Issue by cl1ckname** [Allaman/emoji.nvim#29]
For example. If I use `plugin_path = vim.fn.expand("$HOME/.local/share/nvim/site/pack"),` I get `Error detected while processing InsertEnter Autocommands for "*":  cannot open data file at '/home/clickname/.local/share/nvim/site/packemoji.nvim/lua/data/emojis.json'` error. Maybe it make sense to format the path before using it?

**Comment by Allaman** [comment]
thanks for your feedback. Please checkout the new version

**Comment by cl1ckname** [comment]
Yeah, that's it, thank you
