### ISSUE TITLE
Bug: `emoji.nvim` stops all other completion sources from loading

### ISSUE THREAD

**Issue by chrisgrieser** [Allaman/emoji.nvim#5]
Not sure what exactly is happening here, but it appears that `emoji.nvim` is preventing all other sources from being loaded. The emoji completions itself work fine though.

A look at `:CmpStatus` reveals that, indeed, only `emoji` is loaded:

```
 # ready source names 
 - emoji 
 # unused source names 
 - path 
 - cmdline 
 - buffer 
 - luasnip 
```

**Comment by farzadmf** [comment]
Same here

**Comment by farzadmf** [comment]
Which makes sense because it seems like [this line](https://github.com/Allaman/emoji.nvim/blob/main/lua/emoji/init.lua#L22) is basically replacing all sources with `emoji` only

@Allaman would you be able to take a look?

**Comment by Allaman** [comment]
It should be fixed, can you please confirm? <img width="530" alt="image" src="https://github.com/Allaman/emoji.nvim/assets/12184268/20adcb01-e716-432f-bc93-c3f68acc3c36">

**Comment by chrisgrieser** [comment]
can confirm, problem is fixed. Thanks!
